import {
  addDays,
  compareISO,
  dateRange,
  formatMD,
  subtractBusinessDays,
  subtractCalendarDaysAvoiding,
  todayISO,
  weekdayIndex,
} from './dateUtils';
import courseDeadlines from '../data/course-deadlines.generated.json';

export const makeId = () =>
  `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;

export const FIXED_SCHEDULE = [
  { id: 'work', label: '근무·수업', weekdays: [1, 2, 3, 4, 5], time: '08:00–17:00' },
  { id: 'friday-vigil', label: '금요철야', weekdays: [5], time: '20:00–22:00' },
  {
    id: 'church',
    label: '교회 일정',
    weekdays: [0],
    time: '09:00–16:00 (8월엔 13:30까지)',
    note: (iso) => (iso.slice(0, 7) === '2026-08' ? '8월엔 09:00–13:30' : null),
  },
];

export const getFixedScheduleForDate = (iso) => {
  const day = weekdayIndex(iso);
  return FIXED_SCHEDULE.filter((f) => f.weekdays.includes(day)).map((f) => ({
    ...f,
    time: f.note && f.note(iso) ? f.note(iso) : f.time,
  }));
};

// ---- auto-generators -------------------------------------------------

// 교과: N business days before class. 비교과: N calendar days before, nudged off weekends/exclusions.
// 온라인 (supervision-only classes): same day, light check-in — no lead time.
export const generateCourseTasks = (courses, windowStart, windowEnd, excludedDates) => {
  const tasks = [];
  const scanEnd = addDays(windowEnd, 10);
  for (const course of courses) {
    if (course.active === false) continue;
    for (const occ of dateRange(windowStart, scanEnd)) {
      if (!course.weekdays.includes(weekdayIndex(occ))) continue;
      if (course.startDate && compareISO(occ, course.startDate) < 0) continue;
      const due =
        course.type === 'core'
          ? subtractBusinessDays(occ, course.leadDays, excludedDates)
          : course.type === 'online'
          ? occ
          : subtractCalendarDaysAvoiding(occ, course.leadDays, excludedDates);
      if (compareISO(due, windowStart) < 0 || compareISO(due, windowEnd) > 0) continue;
      tasks.push({
        autoKey: `course:${course.id}:${occ}`,
        title:
          course.type === 'online'
            ? `${course.name} — 진도 확인·채점 (${formatMD(occ)})`
            : `${course.name} 수업 준비 (${formatMD(occ)} 수업)`,
        category: course.type,
        date: due,
        originalDate: due,
        priority: 'deadline',
        notes: '',
        done: false,
      });
    }
  }
  return tasks;
};

const KIND_LABEL = { study_guide: 'Study Guide 준비', test_and_answer_key: 'Test·Answer Key 준비' };

// Real BJU-textbook assessment deadlines synced from holga-course-agent
// (config/courses.generated.yaml, computed there via course_registry.material_tasks():
// 7 calendar days before the assessment, +4 more if the date is only estimated from a
// week range). This is separate from generateCourseTasks' generic per-class-day prep —
// that covers routine daily lesson prep, this covers the periodic study-guide/test push
// for a specific graded assessment. src/data/course-deadlines.generated.json is
// regenerated by a scheduled sync from the other repo; don't hand-edit it.
export const generateAssessmentPrepTasks = (windowStart, windowEnd) => {
  const tasks = [];
  for (const item of courseDeadlines.items) {
    if (compareISO(item.due, windowStart) < 0 || compareISO(item.due, windowEnd) > 0) continue;
    const chapters = item.chapters.length > 1 ? `Ch${item.chapters[0]}-${item.chapters.at(-1)}` : `Ch${item.chapters[0]}`;
    const estimatedTag = item.dateStatus === 'estimated' ? ' (추정일)' : '';
    tasks.push({
      autoKey: `assess:${item.courseId}:${item.textbook}:${item.chapters.join('-')}:${item.kind}`,
      title: `${item.courseName} — ${item.textbook} ${chapters} ${KIND_LABEL[item.kind]} (${formatMD(item.eventDate)} 시험${estimatedTag})`,
      category: 'core',
      date: item.due,
      originalDate: item.due,
      priority: 'deadline',
      notes: '',
      done: false,
      project: item.label,
    });
  }
  return tasks;
};

export const generateExerciseTasks = (windowStart, windowEnd, weekdays) => {
  const tasks = [];
  for (const iso of dateRange(windowStart, windowEnd)) {
    if (!weekdays.includes(weekdayIndex(iso))) continue;
    tasks.push({
      autoKey: `exercise:${iso}`,
      title: '운동 40분',
      category: 'exercise',
      date: iso,
      originalDate: iso,
      priority: 'normal',
      notes: '',
      done: false,
    });
  }
  return tasks;
};

// Spreads a project's remaining units one-per-available-day across [startDate, endDate],
// skipping blockoutDates. If more units than days, later units double up on the last days.
export const generateReviewProjectTasks = (project) => {
  const available = dateRange(project.startDate, project.endDate).filter(
    (d) => !project.blockoutDates.includes(d)
  );
  if (available.length === 0 || project.units.length === 0) return [];
  return project.units.map((unit, idx) => {
    const day = available[Math.min(idx, available.length - 1)];
    return {
      autoKey: `review:${project.id}:${unit.id}`,
      title: `${project.name} — ${unit.label}`,
      category: 'review',
      date: day,
      originalDate: day,
      priority: unit.deadline ? 'deadline' : 'normal',
      notes: '',
      done: false,
      project: project.name,
    };
  });
};

// Preserve done/notes/current(possibly rolled-over) date for tasks that already existed.
export const mergeAutoTasks = (existingTasks, freshAutoTasks) => {
  const existingByKey = new Map(
    existingTasks.filter((t) => t.autoKey).map((t) => [t.autoKey, t])
  );
  const manualTasks = existingTasks.filter((t) => !t.autoKey);
  const freshKeys = new Set(freshAutoTasks.map((t) => t.autoKey));

  const merged = freshAutoTasks.map((fresh) => {
    const prior = existingByKey.get(fresh.autoKey);
    if (prior) {
      return {
        ...fresh,
        id: prior.id,
        done: prior.done,
        notes: prior.notes,
        date: prior.date,
        createdAt: prior.createdAt,
      };
    }
    return { ...fresh, id: makeId(), createdAt: Date.now() };
  });

  // Auto tasks whose source no longer produces them (window moved on, project edited)
  // are kept as-is rather than silently deleted, so history isn't lost.
  const orphaned = existingTasks.filter((t) => t.autoKey && !freshKeys.has(t.autoKey));

  return [...manualTasks, ...orphaned, ...merged];
};

export const regenerateAutoTasks = (state) => {
  const windowStart = todayISO();
  const windowEnd = addDays(windowStart, 13);
  const fresh = [
    ...generateCourseTasks(state.courses, windowStart, windowEnd, state.excludedDates),
    ...generateAssessmentPrepTasks(windowStart, windowEnd),
    ...generateExerciseTasks(windowStart, windowEnd, state.exerciseWeekdays),
    ...state.reviewProjects.flatMap(generateReviewProjectTasks),
  ];
  return mergeAutoTasks(state.tasks, fresh);
};

// Any undone task whose date has passed rolls forward onto today.
export const applyRollover = (tasks, todayIso) =>
  tasks.map((t) => {
    if (!t.done && compareISO(t.date, todayIso) < 0) {
      return { ...t, date: todayIso, rolledOver: true };
    }
    return t;
  });

// ---- real courses, read from "교사 Time Schedule_2026 가을" (Mr. Ko's row) in Drive ----
// startDate is the first real class day of the term (2026-08-26, Wed) — combined with the
// weekday filter this naturally reproduces the school's actual quirk where Mon/Tue-only
// subjects don't meet at all in the opening week (8/24–8/25 fall before the term starts).

export const DEFAULT_COURSES = [
  { id: 'math-g9', name: 'Math G9', type: 'core', weekdays: [2, 3, 5], leadDays: 2, startDate: '2026-08-26', active: true },
  { id: 'math-g12', name: 'Math G12', type: 'core', weekdays: [1, 3], leadDays: 2, startDate: '2026-08-26', active: true },
  { id: 'science-g4', name: 'Science G4', type: 'core', weekdays: [1, 4], leadDays: 2, startDate: '2026-08-26', active: true },
  { id: 'science-g7k', name: '과학 G7K', type: 'core', weekdays: [1, 2], leadDays: 2, startDate: '2026-08-26', active: true },
  { id: 'sci-exp-g3-6', name: 'Science Experiment G3-6', type: 'noncore', weekdays: [1], leadDays: 7, startDate: '2026-08-26', active: true },
  { id: 'sci-exp-g7-12', name: 'Science Experiment G7-12', type: 'noncore', weekdays: [4], leadDays: 7, startDate: '2026-08-26', active: true },
  { id: 'ca-newspaper', name: 'C.A. (학교신문)', type: 'noncore', weekdays: [5], leadDays: 7, startDate: '2026-08-26', active: true },
  { id: 'musical-speaking', name: 'Musical Speaking G4-12', type: 'noncore', weekdays: [3], leadDays: 6, startDate: '2026-08-26', active: true },
  { id: 'speaking-g4', name: 'Speaking G4', type: 'noncore', weekdays: [2], leadDays: 6, startDate: '2026-08-26', active: true },
  {
    id: 'online-science',
    name: '온라인 Science (G7E/G9/G12)',
    type: 'online',
    weekdays: [2, 3, 4, 5],
    leadDays: 0,
    startDate: '2026-08-26',
    active: true,
  },
];

// One-off setup work for brand-new heavy courses — the recurring 1-2일/5-7일 rule only
// covers steady-state weekly prep, not building a course's system from scratch.
export const SCHOOL_SETUP_TASKS = [
  {
    title: 'Science Experiment G3-6 — 재료 확보 + Outdoor Earth Detective Walk 활동지 제작',
    category: 'noncore',
    date: '2026-08-16',
    priority: 'deadline',
    project: 'Science Experiment G3-6',
  },
  {
    title: 'Science Experiment G7-12 — OT 자료·안전규칙·발표 rubric·rotation·topic approval 제작',
    category: 'noncore',
    date: '2026-08-17',
    priority: 'deadline',
    project: 'Science Experiment G7-12',
  },
  {
    title: 'Musical Speaking — 재사용 가능한 warm-up/diction 루틴 세트 제작',
    category: 'noncore',
    date: '2026-08-19',
    priority: 'deadline',
    project: 'Musical Speaking',
  },
  {
    title: 'Speaking G4 — 첫 2주 자료 제작',
    category: 'noncore',
    date: '2026-08-20',
    priority: 'deadline',
    project: 'Speaking G4',
  },
  {
    title: '개학 Launch Check — 수/목/금 자료 최종 확인, 인쇄, 온라인 Science 링크 테스트',
    category: 'other',
    date: '2026-08-25',
    priority: 'deadline',
  },
];

// ---- seed data (the real plan carried over from the ChatGPT conversation) ----

export const buildSeedState = () => {
  const manualTasks = [
    {
      title: '3·4층 피난안내도 4개 부착 및 현장 방향 검수',
      category: 'urgent',
      date: '2026-08-18',
    },
    ...SCHOOL_SETUP_TASKS,
    {
      title: '방 정리 — 전체 분류 및 바닥 통로 확보',
      category: 'room',
      date: '2026-08-15',
    },
    { title: '방 정리 — 옷·가방·침구', category: 'room', date: '2026-08-17' },
    {
      title: '방 정리 — 책상·책·서류·전자기기',
      category: 'room',
      date: '2026-08-22',
    },
    { title: '방 정리 — 서랍·선반·잡동사니', category: 'room', date: '2026-08-23' },
    { title: '방 정리 — 배출·청소·최종 배치', category: 'room', date: '2026-08-29' },
    {
      title: '하이성 2 — 통합 QA (일관성·인용·쪽수 점검)',
      category: 'review',
      date: '2026-08-27',
      priority: 'deadline',
      project: '하이성 2',
    },
    {
      title: '하이성 2 — 최종 점검 및 완료 → 하이성 3 착수 준비',
      category: 'review',
      date: '2026-08-28',
      priority: 'deadline',
      project: '하이성 2',
    },
  ].map((t) => ({
    id: makeId(),
    priority: 'normal',
    notes: '',
    done: false,
    autoKey: null,
    createdAt: Date.now(),
    ...t,
  }));

  const chapterUnits = [9, 10, 11, 12, 13, 14, 15, 16].map((n) => ({
    id: `ch${n}`,
    label: `${n}장 감수`,
  }));

  const reviewProjects = [
    {
      id: 'haiseong-2-review',
      name: '하이성 2',
      startDate: '2026-08-15',
      endDate: '2026-08-26',
      blockoutDates: ['2026-08-18', '2026-08-24'],
      units: [
        ...chapterUnits,
        { id: 'buf1', label: '9–16장 보충·재검토' },
        { id: 'buf2', label: '여유 세션 (오탈자·보충)' },
      ],
    },
    {
      id: 'haiseong-3-review',
      name: '하이성 3',
      startDate: '2026-08-29',
      endDate: '2026-08-29',
      blockoutDates: [],
      units: [{ id: 'manuscript-needed', label: '원고 필요 — 목차만 있고 쪽수 미정' }],
    },
  ];

  return {
    tasks: manualTasks,
    courses: DEFAULT_COURSES,
    reviewProjects,
    excludedDates: ['2026-08-18', '2026-08-24'],
    exerciseWeekdays: [1, 2, 4],
  };
};
